"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from typing import List, Optional

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _str_to_bool(value: Optional[str], default: bool = False) -> bool:
    """Convert common string toggles to bool."""
    if value is None:
        return default
    return value.strip().lower() in {'1', 'true', 'yes', 'on'}


def _csv_to_list(value: Optional[str], default: Optional[List[str]] = None) -> List[str]:
    if not value:
        return list(default or [])
    return [item.strip() for item in value.split(',') if item.strip()]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-$nk=#7=5q!h%4oymngd+cc(3=px++e7y73+uwc9ns!nqyf6!^w'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _str_to_bool(os.getenv('DJANGO_DEBUG', os.getenv('DEBUG')), default=True)

_default_hosts = ['localhost', '127.0.0.1', '0.0.0.0'] if DEBUG else []
ALLOWED_HOSTS = _csv_to_list(
    os.getenv('DJANGO_ALLOWED_HOSTS', os.getenv('ALLOWED_HOSTS')),
    default=_default_hosts,
)

render_host = os.getenv('RENDER_EXTERNAL_HOSTNAME')
if render_host:
    ALLOWED_HOSTS.append(render_host)

ALLOWED_HOSTS = list(dict.fromkeys(ALLOWED_HOSTS))


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'drf_spectacular',
    'django_filters',
    'django_extensions',
    'tasks',
    'tenders',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'core.middleware.RequestLoggingMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

REST_FRAMEWORK = {
    # Configuration pour la génération automatique du schéma OpenAPI (drf-spectacular).
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_FILTER_BACKENDS': [
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
        'django_filters.rest_framework.DjangoFilterBackend',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 5,
}

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
MEDIA_ROOT.mkdir(parents=True, exist_ok=True)

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Logging configuration: write to logs/taskflow.log and to console.
LOGS_DIR = BASE_DIR / 'logs'
# Ensure logs directory exists so FileHandler does not fail when Django configures logging.
LOGS_DIR.mkdir(parents=True, exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'standard': {
            # Met l'horodatage entre crochets. Exemple : [2025-10-23 09:54:00,092]
            'format': '[%(asctime)s] [%(levelname)s] %(name)s: %(message)s'
        },
        'request': {
            'format': '[%(asctime)s] [%(levelname)s] %(message)s'
        }
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'standard',
        },
        'file': {
            # Use RotatingFileHandler to avoid growing logs indefinitely.
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': str(LOGS_DIR / 'taskflow.log'),
            'formatter': 'request',
            'encoding': 'utf-8',
            'maxBytes': 10 * 1024 * 1024,  # 10 MB
            'backupCount': 5,
            'delay': True,
        },
    },
    'loggers': {
        '': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
        },
        'django.request': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
    }
}

# Paramètres pour drf-spectacular (OpenAPI schema)
SPECTACULAR_SETTINGS = {
    'TITLE': 'Taskflow API',
    'DESCRIPTION': 'API pour gérer des tâches (Taskflow). Documentation auto-générée.',
    'VERSION': '1.0.0',
}

# Option A (démo) : utiliser un jeu de données statique quand demandé.
TASKFLOW_USE_DEMO_DATA = os.getenv('TASKFLOW_USE_DEMO_DATA', '').lower() in {'1', 'true', 'yes', 'on'}
TASKFLOW_DEMO_FILE = Path(os.getenv('TASKFLOW_DEMO_FILE', str(BASE_DIR / 'demo_tasks.json')))
