# Generated by Django 5.2.7 on 2025-10-21 07:47

import tasks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('A faire', 'A faire'), ('En cours', 'En cours'), ('Fait', 'Fait')], default='A faire', max_length=20, validators=[tasks.models.validate_status]),
        ),
    ]
