# Generated by Django 5.2.7 on 2025-10-21 07:55

import tasks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('todo', 'A faire'), ('in_progress', 'En cours'), ('done', 'Fait')], default='todo', max_length=20, validators=[tasks.models.validate_status]),
        ),
    ]
