# Generated by Django 5.2.7 on 2025-10-21 08:17

import tasks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(default='A faire', max_length=20, validators=[tasks.models.validate_status]),
        ),
    ]
