# Generated by Django 5.2.8 on 2025-11-14 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_task_due_date_task_module_task_priority_and_more'),
        ('tasks', '0013_task_metadata'),
    ]

    operations = [
    ]
