# Generated by Django 5.2.8 on 2025-11-14 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['name', 'id']},
        ),
    ]
